name: alias_short
description: A command-line tool for simplifying Flutter commands with aliases.
version: 1.0.4
repository: https://github.com/Erihmar1259/alias_short
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.5
license: MIT
# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
executables:
  alias_short: alias_short
dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
